#!/usr/bin/env python3
"""Emit deterministic SQL and fixture metadata for local Rougether scale runs."""

from __future__ import annotations

import argparse
import datetime as dt
import io
import json
import sys
from pathlib import Path


DEFAULT_USER_START = 900_000_000
DEFAULT_TODO_START = 910_000_000
DEFAULT_WALLET_START = 920_000_000
DEFAULT_SEED_ID = "rougether-scale-v1"
DEFAULT_DB_NAME = "rougether_scale"
REWARD_AMOUNT = 10
DAILY_REWARD_CAP = 50


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def iso_date(value: str) -> str:
    try:
        return dt.date.fromisoformat(value).isoformat()
    except ValueError as exc:
        raise argparse.ArgumentTypeError("must be YYYY-MM-DD") from exc


def sql_quote(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    text = str(value)
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def batched(items, size: int):
    batch = []
    for item in items:
        batch.append(item)
        if len(batch) == size:
            yield batch
            batch = []
    if batch:
        yield batch


def database_guard_sql(database_name: str) -> str:
    return "\n".join(
        [
            "DELIMITER //",
            "CREATE PROCEDURE rougether_scale_seed_guard()",
            "BEGIN",
            f"  IF DATABASE() <> {sql_quote(database_name)} THEN",
            "    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Refusing to seed outside rougether scale database';",
            "  END IF;",
            "END//",
            "DELIMITER ;",
            "CALL rougether_scale_seed_guard();",
            "DROP PROCEDURE rougether_scale_seed_guard;",
        ]
    )


def row_values(rows: list[tuple[object, ...]]) -> str:
    return ",\n".join("(" + ", ".join(sql_quote(value) for value in row) + ")" for row in rows)


def write_insert(out, table: str, columns: tuple[str, ...], rows, batch_size: int) -> None:
    for batch in batched(rows, batch_size):
        out.write(f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n")
        out.write(row_values(batch))
        out.write(";\n")


def iter_user_rows(args: argparse.Namespace, now: str):
    for idx in range(args.users):
        yield (
            args.user_start + idx,
            f"scale-{idx:06d}@rougether.local",
            f"scale-user-{idx:06d}",
            now,
            now,
            None,
            False,
            None,
        )


def iter_wallet_rows(args: argparse.Namespace, now: str):
    for idx in range(args.users):
        for offset, currency in enumerate(("COIN", "DIAMOND")):
            yield (
                args.wallet_start + idx * 2 + offset,
                args.user_start + idx,
                currency,
                0,
                now,
                now,
            )


def iter_room_rows(args: argparse.Namespace, now: str):
    for idx in range(args.users):
        yield (
            args.user_start + idx,
            0,
            now,
            "SLOT_V1",
            0,
            0,
            0,
        )


def iter_todo_rows(args: argparse.Namespace, now: str):
    for ordinal in range(args.todo_count):
        yield (
            args.todo_start + ordinal,
            args.user_start + (ordinal % args.users),
            None,
            f"scale todo {ordinal}",
            None,
            args.date,
            None,
            "PENDING",
            None,
            None,
            0,
            now,
            now,
            None,
            None,
            None,
            0,
        )


def write_sql(args: argparse.Namespace, out) -> None:
    now = args.timestamp
    users_count = args.users
    todo_count = args.todo_count
    user_end = args.user_start + users_count - 1
    todo_end = args.todo_start + todo_count - 1
    wallet_end = args.wallet_start + users_count * 2 - 1

    for statement in (
        "-- Generated by qa/scale/seed/seed_scale_db.py; local isolated DB only.",
        database_guard_sql(args.database_name),
        "SET FOREIGN_KEY_CHECKS = 1;",
        "START TRANSACTION;",
        f"DELETE FROM wallet_histories WHERE source_type = 'TODO' AND source_id BETWEEN {args.todo_start} AND {todo_end};",
        f"DELETE FROM todos WHERE id BETWEEN {args.todo_start} AND {todo_end};",
        f"DELETE FROM user_daily_activity WHERE user_id BETWEEN {args.user_start} AND {user_end};",
        f"DELETE FROM personal_rooms WHERE user_id BETWEEN {args.user_start} AND {user_end};",
        f"DELETE FROM user_wallets WHERE id BETWEEN {args.wallet_start} AND {wallet_end};",
        f"DELETE FROM user_wallets WHERE user_id BETWEEN {args.user_start} AND {user_end};",
        f"DELETE FROM oauth_accounts WHERE user_id BETWEEN {args.user_start} AND {user_end};",
        f"DELETE FROM users WHERE id BETWEEN {args.user_start} AND {user_end};",
    ):
        out.write(statement)
        out.write("\n")
    write_insert(
        out,
        "users",
        ("id", "email", "nickname", "created_at", "updated_at", "deleted_at", "is_bot", "bot_key"),
        iter_user_rows(args, now),
        args.batch_size,
    )
    write_insert(
        out,
        "user_wallets",
        ("id", "user_id", "currency_type", "balance", "created_at", "updated_at"),
        iter_wallet_rows(args, now),
        args.batch_size,
    )
    write_insert(
        out,
        "personal_rooms",
        (
            "user_id",
            "growth_level",
            "updated_at",
            "layout_format",
            "layout_revision",
            "growth_points",
            "highest_growth_level",
        ),
        iter_room_rows(args, now),
        args.batch_size,
    )
    write_insert(
        out,
        "todos",
        (
            "id",
            "user_id",
            "category_id",
            "title",
            "description",
            "due_date",
            "due_time",
            "status",
            "completed_at",
            "reward_currency_type",
            "reward_amount",
            "created_at",
            "updated_at",
            "deleted_at",
            "external_source",
            "external_id",
            "growth_reward_amount",
        ),
        iter_todo_rows(args, now),
        args.batch_size,
    )
    for statement in (
        "COMMIT;",
        f"SELECT COUNT(*) AS scale_users FROM users WHERE id BETWEEN {args.user_start} AND {user_end};",
        f"SELECT COUNT(*) AS scale_todos FROM todos WHERE id BETWEEN {args.todo_start} AND {todo_end};",
    ):
        out.write(statement)
        out.write("\n")


def build_sql(args: argparse.Namespace) -> str:
    out = io.StringIO()
    write_sql(args, out)
    return out.getvalue()


def build_fixture(args: argparse.Namespace) -> dict:
    todo_count = args.todo_count
    return {
        "schemaVersion": 1,
        "seedId": args.seed_id,
        "databaseName": args.database_name,
        "date": args.date,
        "createdAt": args.timestamp,
        "userStartId": args.user_start,
        "usersCount": args.users,
        "todoStartId": args.todo_start,
        "todoSlotsPerUserCeil": (todo_count + args.users - 1) // args.users,
        "todoCount": todo_count,
        "mapping": {
            "strategy": "round_robin_ordinal",
            "todoId": "todoStartId + ordinal",
            "ownerUserId": "userStartId + (ordinal % usersCount)",
        },
        "seedProfile": {
            "users": {
                "active": True,
                "bot": False,
                "nicknamePattern": "scale-user-%06d",
                "emailPattern": "scale-%06d@rougether.local",
                "onboardingCompleted": False,
            },
            "wallets": {"currencies": ["COIN", "DIAMOND"], "initialBalance": 0},
            "personalRooms": {
                "growthLevel": 0,
                "growthPoints": 0,
                "highestGrowthLevel": 0,
                "layoutFormat": "SLOT_V1",
            },
            "todos": {
                "status": "PENDING",
                "dueDate": args.date,
                "categoryId": None,
                "rewardAmount": 0,
                "growthRewardAmount": 0,
            },
        },
        "reward": {
            "currency": "COIN",
            "todoCompleteAmount": REWARD_AMOUNT,
            "dailyCap": DAILY_REWARD_CAP,
        },
        "endpoints": {
            "me": "GET /api/v1/me",
            "today": "GET /api/v1/today",
            "completeTodo": "POST /api/v1/todos/{id}/complete",
        },
        "expectedDuplicate": {
            "status": 409,
            "code": "TODO_ALREADY_COMPLETED",
        },
        "jwt": {
            "algorithm": "HS256",
            "claims": {"typ": "access", "role": "NORMAL"},
            "secretSource": "runner env JWT_SECRET",
        },
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    today = dt.datetime.now(dt.timezone(dt.timedelta(hours=9))).date().isoformat()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--users", type=positive_int, default=1000)
    parser.add_argument("--todos-per-user", type=positive_int, default=10)
    parser.add_argument("--todo-count", type=positive_int)
    parser.add_argument("--date", type=iso_date, default=today)
    parser.add_argument("--user-start", type=positive_int, default=DEFAULT_USER_START)
    parser.add_argument("--todo-start", type=positive_int, default=DEFAULT_TODO_START)
    parser.add_argument("--wallet-start", type=positive_int, default=DEFAULT_WALLET_START)
    parser.add_argument("--seed-id", default=DEFAULT_SEED_ID)
    parser.add_argument("--database-name", default=DEFAULT_DB_NAME)
    parser.add_argument("--batch-size", type=positive_int, default=1000)
    parser.add_argument("--timestamp", default=dt.datetime.now(dt.timezone.utc).replace(microsecond=0).strftime("%Y-%m-%d %H:%M:%S"))
    parser.add_argument("--sql-out", type=Path)
    parser.add_argument("--fixture-json", type=Path, required=True)
    args = parser.parse_args(argv)
    if args.todo_count is None:
        args.todo_count = args.users * args.todos_per_user
    return args


def validate_ranges(args: argparse.Namespace) -> None:
    todo_count = args.todo_count
    ranges = [
        ("users", args.user_start, args.user_start + args.users - 1),
        ("todos", args.todo_start, args.todo_start + todo_count - 1),
        ("wallets", args.wallet_start, args.wallet_start + args.users * 2 - 1),
    ]
    for idx, (left_name, left_start, left_end) in enumerate(ranges):
        for right_name, right_start, right_end in ranges[idx + 1 :]:
            if max(left_start, right_start) <= min(left_end, right_end):
                raise SystemExit(f"{left_name} id range overlaps {right_name} id range")
    if args.batch_size > 5000:
        raise SystemExit("--batch-size above 5000 makes review and mysql errors painful")
    if args.database_name != DEFAULT_DB_NAME:
        raise SystemExit("--database-name must be rougether_scale")


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    validate_ranges(args)
    fixture = build_fixture(args)
    args.fixture_json.parent.mkdir(parents=True, exist_ok=True)
    args.fixture_json.write_text(json.dumps(fixture, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.sql_out:
        args.sql_out.parent.mkdir(parents=True, exist_ok=True)
        with args.sql_out.open("w", encoding="utf-8") as out:
            write_sql(args, out)
    else:
        write_sql(args, sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
