plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'rougether-server'

include 'common'
include 'domain'
include 'infra:fcm'
include 'infra:llm'
include 'user-api'
include 'admin-api'
include 'batch'

include 'infra:assets'
include 'furniture-application'
include 'furniture-worker'
include 'furniture-lambda-ai'
include 'furniture-lambda-control'
include 'furniture-preprocessing'
include 'furniture-lambda-preprocess'
