#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOTSTRAP_SCRIPT="$SCRIPT_DIR/bootstrap-blue-green-router.sh"
TEST_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/rougether-bootstrap-test.XXXXXX")"
trap 'rm -rf "$TEST_ROOT"' EXIT

FUNCTIONS_FILE="$TEST_ROOT/nginx-functions.sh"
awk '
  /^# BEGIN_NGINX_FUNCTIONS$/ { capture = 1; next }
  /^# END_NGINX_FUNCTIONS$/ { capture = 0 }
  capture { print }
' "$BOOTSTRAP_SCRIPT" > "$FUNCTIONS_FILE"
# shellcheck source=/dev/null
source "$FUNCTIONS_FILE"

NGINX_CONFIG_DIR="$TEST_ROOT/nginx"
NGINX_CONFIG_FILE="$NGINX_CONFIG_DIR/rougether.conf"
private_ip="10.39.10.37"
mkdir -p "$NGINX_CONFIG_DIR"

fail_validation=false
fail_reload_once=false
fail_admin_start=false
reload_calls=0
systemctl_log="$TEST_ROOT/systemctl.log"

nginx() {
  [ "${1:-}" = "-t" ] || return 2
  if [ "$fail_validation" = true ] && [ -f "$NGINX_CONFIG_FILE" ] \
      && grep -q '^# Generated by bootstrap-blue-green-router.sh' "$NGINX_CONFIG_FILE"; then
    return 1
  fi
}

systemctl() {
  printf '%s\n' "$*" >> "$systemctl_log"
  case "$1 ${2:-}" in
    "is-active --quiet") return 0 ;;
    "reload nginx")
      reload_calls=$(( reload_calls + 1 ))
      if [ "$fail_reload_once" = true ]; then
        fail_reload_once=false
        return 1
      fi
      ;;
    "enable --now") return 0 ;;
    "start rougether-admin-api")
      [ "$fail_admin_start" = false ]
      ;;
    *) return 0 ;;
  esac
}

assert_file_equals() {
  local expected="$1" actual="$2"
  [ "$(cat "$actual")" = "$expected" ] || {
    echo "expected $actual to contain the previous configuration" >&2
    exit 1
  }
}

test_validation_failure_restores_existing_config() {
  local previous='previous nginx config'
  printf '%s\n' "$previous" > "$NGINX_CONFIG_FILE"
  fail_validation=true
  reload_calls=0

  if apply_nginx 18080 18081; then
    echo "expected invalid candidate Nginx configuration to fail" >&2
    exit 1
  fi

  fail_validation=false
  assert_file_equals "$previous" "$NGINX_CONFIG_FILE"
  [ "$reload_calls" -eq 1 ] || {
    echo "expected restored Nginx configuration to be reloaded once" >&2
    exit 1
  }
}

test_validation_failure_removes_new_config_without_backup() {
  rm -f "$NGINX_CONFIG_FILE"
  fail_validation=true
  reload_calls=0

  if apply_nginx 18080 18081; then
    echo "expected invalid first Nginx configuration to fail" >&2
    exit 1
  fi

  fail_validation=false
  [ ! -e "$NGINX_CONFIG_FILE" ] || {
    echo "expected failed first Nginx configuration to be removed" >&2
    exit 1
  }
}

test_reload_failure_restores_existing_config() {
  local previous='reload-safe previous config'
  printf '%s\n' "$previous" > "$NGINX_CONFIG_FILE"
  fail_reload_once=true
  reload_calls=0

  if apply_nginx 18080 18081; then
    echo "expected candidate Nginx reload to fail" >&2
    exit 1
  fi

  assert_file_equals "$previous" "$NGINX_CONFIG_FILE"
  [ "$reload_calls" -eq 2 ] || {
    echo "expected one failed candidate reload and one successful restore reload" >&2
    exit 1
  }
}

test_success_replaces_config_and_removes_backup() {
  printf '%s\n' 'old config' > "$NGINX_CONFIG_FILE"
  reload_calls=0
  apply_nginx 18080 18081

  grep -q 'server 127.0.0.1:18080' "$NGINX_CONFIG_FILE"
  grep -q 'server 10.39.10.37:18081' "$NGINX_CONFIG_FILE"
  [ "$reload_calls" -eq 1 ]
  [ -z "$(find "$NGINX_CONFIG_DIR" -name '.rougether.conf.backup.*' -print -quit)" ]
}

test_activation_rollback_restores_legacy_before_stopping_candidates() {
  : > "$systemctl_log"
  render_nginx 18080 18081 "$NGINX_CONFIG_FILE"
  user_legacy_stopped=true
  admin_legacy_stopped=true

  local exit_code=0
  set +e
  ( set +e; false; rollback_activation ) >/dev/null 2>&1
  exit_code="$?"
  set -e

  [ "$exit_code" -eq 1 ]
  grep -q '^start rougether-admin-api$' "$systemctl_log"
  grep -q '^stop rougether-admin-api@blue$' "$systemctl_log"
  grep -q '^start rougether-user-api$' "$systemctl_log"
  grep -q '^stop rougether-user-api@blue$' "$systemctl_log"
  if grep -q 'listen 8080\|listen 8081' "$NGINX_CONFIG_FILE"; then
    echo "expected successful rollback to release both fixed ports" >&2
    exit 1
  fi
}

test_failed_legacy_restart_keeps_candidate_routing_and_containers() {
  : > "$systemctl_log"
  render_nginx 18080 18081 "$NGINX_CONFIG_FILE"
  user_legacy_stopped=true
  admin_legacy_stopped=true
  fail_admin_start=true

  local exit_code=0
  set +e
  ( set +e; false; rollback_activation ) >/dev/null 2>&1
  exit_code="$?"
  set -e
  fail_admin_start=false

  [ "$exit_code" -eq 1 ]
  grep -q 'server 127.0.0.1:18080' "$NGINX_CONFIG_FILE"
  grep -q 'server 10.39.10.37:18081' "$NGINX_CONFIG_FILE"
  if grep -q '^stop rougether-admin-api@blue$\|^stop rougether-user-api@blue$\|^start rougether-user-api$' "$systemctl_log"; then
    echo "expected candidate services to stay available after failed legacy restart" >&2
    exit 1
  fi
}

test_validation_failure_restores_existing_config
test_validation_failure_removes_new_config_without_backup
test_reload_failure_restores_existing_config
test_success_replaces_config_and_removes_backup
test_activation_rollback_restores_legacy_before_stopping_candidates
test_failed_legacy_restart_keeps_candidate_routing_and_containers

echo "bootstrap blue/green router tests passed"
